from datetime import datetime
from helpers import obfuscate_prompt_username
from server_extensions import db, ma

PAGINATION_ROW_COUNT = 25

class Message(db.Model):
  """Keeps track of all messages generated by Luna on Twitch."""

  id = db.Column(
    db.Integer,
    primary_key=True,
    autoincrement=True
  )
  created_at = db.Column(
    db.DateTime,
    nullable=False,
    default=datetime.now
  )
  prompt = db.Column(
    db.Text,
    nullable=False
  )
  response = db.Column(
    db.Text,
    nullable=False
  )
  latency_llm = db.Column(
    db.Float,
    nullable=False,
  )
  latency_tts = db.Column(
    db.Float,
    nullable=False,
  )
class MessageSchema(ma.SQLAlchemySchema):
  class Meta:
    model = Message
  id=ma.auto_field()
  created_at=ma.auto_field()
  prompt=ma.auto_field()
  response=ma.auto_field()
  latency_llm=ma.auto_field()
  latency_tts=ma.auto_field()
message_schema = MessageSchema()
messages_schema = MessageSchema(many=True)
def db_message_get_by_page(page):
  rows = Message.query \
    .order_by(Message.created_at.desc()) \
    .offset((page - 1) * PAGINATION_ROW_COUNT) \
    .limit(PAGINATION_ROW_COUNT) \
    .all()
  return messages_schema.dump(rows)
def db_message_insert_one(prompt, response, latency_llm, latency_tts):
  row = Message(
    prompt=obfuscate_prompt_username(prompt),
    response=response,
    latency_llm=latency_llm,
    latency_tts=latency_tts
  )
  db.session.add(row)
  db.session.commit()
def db_message_get_last_five():
  rows = Message.query.order_by(Message.created_at.desc()).limit(5).all()
  return messages_schema.dump(rows)

class Event(db.Model):
  """Keeps track of twitch event usage, such as channel point redemptions & chat commands."""

  id = db.Column(
    db.Integer,
    primary_key=True,
    autoincrement=True
  )
  created_at = db.Column(
    db.DateTime,
    nullable=False,
    default=datetime.now
  )
  type = db.Column(
    db.Text, # should ideally be enum based on TWITCH_EVENT_TYPE
    nullable=False
  )
  event = db.Column(
    db.Text,
    nullable=False
  )
  body = db.Column(
    db.Text,
    nullable=True
  )
class EventSchema(ma.SQLAlchemySchema):
  class Meta:
    model = Event
  id=ma.auto_field()
  created_at=ma.auto_field()
  type=ma.auto_field()
  event=ma.auto_field()
  body=ma.auto_field()
event_schema = EventSchema()
events_schema = EventSchema(many=True)
def db_event_get_by_page(page):
  rows = Event.query \
    .order_by(Event.created_at.desc()) \
    .offset((page - 1) * PAGINATION_ROW_COUNT) \
    .limit(PAGINATION_ROW_COUNT) \
    .all()
  return events_schema.dump(rows)
def db_event_insert_one(type, event, body = None):
  row = Event(
    type=type,
    event=event,
    body=body
  )
  db.session.add(row)
  db.session.commit()
