# this fn was generated by chatgpt
def validate_moderation_ai_payload(data: dict) -> None:
  if not isinstance(data, dict):
    raise ValueError("[MODERATION AI] Payload must be a dictionary.")
  required_fields = {"classification","username","reason","timeoutSeconds"}
  if set(data.keys()) != required_fields:
    missing = required_fields - set(data.keys())
    extra = set(data.keys()) - required_fields
    raise ValueError(f"[MODERATION AI] Invalid fields. Missing: {missing or None}, Extra: {extra or None}")
  if not isinstance(data["classification"], str):
    raise ValueError("[MODERATION AI] classification must be a string.")
  allowed_classifications = {"BAN","UNBAN","TIMEOUT","ERROR"}
  if data["classification"] not in allowed_classifications:
    raise ValueError(f"[MODERATION AI] classification must be one of {allowed_classifications}.")
  if not isinstance(data["username"], str):
    raise ValueError("[MODERATION AI] username must be a string.")
  if not isinstance(data["reason"], str):
    raise ValueError("[MODERATION AI] reason must be a string.")
  if not isinstance(data["timeoutSeconds"], (int, float)):
    raise ValueError("[MODERATION AI] timeoutSeconds must be a number.")
  if data["timeoutSeconds"] < 0:
    raise ValueError("[MODERATION AI] timeoutSeconds cannot be negative.")
  if data["classification"] == "TIMEOUT":
    if data["timeoutSeconds"] <= 0:
      raise ValueError("[MODERATION AI] timeoutSeconds must be > 0 when classification is TIMEOUT.")
  else:
    if data["timeoutSeconds"] != 0:
      raise ValueError("[MODERATION AI] timeoutSeconds must be 0 when classification is not TIMEOUT.")
    